name: publish

on:
  workflow_dispatch:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

env:
  NODE_ENV: "development"
  NODE_VERSION: 20

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: ${{ env.NODE_VERSION }}
          registry-url: "https://registry.npmjs.org"
          scope: "@syntatis"

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Run build
        run: npm run build --workspace=@syntatis/wp-classic-components

      - name: Publish
        run: npm publish --workspace=@syntatis/wp-classic-components
