name: publish

on:
  workflow_dispatch:
    inputs:
      semver:
        description: 'Semver version'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

env:
  NODE_VERSION: 20

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Publish (NPM)
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          npx lerna version ${{ inputs.semver }} --yes
          npx lerna publish from-package --yes
