name: publish

on:
  workflow_dispatch:
    inputs:
      semver:
        description: "SemVer"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

env:
  NODE_VERSION: 20

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Publish (NPM)
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          npx lerna publish from-package --yes
